Repository vtex/vtex-courses, pull requests merged in 2022-07, with the labels that each got.

#218 Fix information divergence between class content and answer sheet reported on issue #217
  courses/layout-blocks/steps/08_stack-layout/answersheet/home.jsonc
Labels: documentation

#160 Corrected import from the store-block-template
  courses/store-block/steps/08_react-apollo/en.md
  courses/store-block/steps/08_react-apollo/pt.md
Labels: content fix

#219 Fix grammar mistake
  courses/basic-blocks/steps/02_richtext/en.md
Labels: typo
